### ISSUE TITLE
Missing requirements.

### ISSUE THREAD

**Issue by roachfr** [newerton/bombcrypto-find-jail-bot#1]
please update the requirements.txt

**Comment by newerton** [comment]
Why?

**Comment by roachfr** [comment]
there's some module called telegram and i have installed all the requirements but it fails to start..

**Comment by newerton** [comment]
Fixed the bot does not use telegram.

**Comment by roachfr** [comment]
still, cant run.
AttributeError: 'Recognition' object has no attribute 'recognition'

**Comment by roachfr** [comment]
remove the class calling in recognition.py on lines 85, 87, 89, 91

**Comment by newerton** [comment]
I fixed it here, checked other files and tested it.

**Comment by newerton** [comment]
> remove the class calling in recognition.py on lines 85, 87, 89, 91

I added importLibs(), because this self.recognition recognizes which screen the bot is on.
